version: 0.2

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip"
      - "unzip terraform_0.12.28_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init
      - terraform $TF_PLAN

  build:
    commands:
      - terraform $TF_APPLY -auto-approve
      - echo terraform $TF_APPLY completed on `date`

  post_build:
    commands:
      - terraform $TF_DESTROY
